// Generated by `risc0-build::embed_methods()` in build.rs.
// Exposes:
//   - ATTESTATION_GUEST_ELF / ATTESTATION_GUEST_ID  — the balance circuit
//   - GENERATE_IDL_ELF / GENERATE_IDL_ID           — IDL generator
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
